# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/gnss_fix.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/gnss_fix.proto\x12\x0enatuition.gnss\"\xf3\x01\n\x07GnssFix\x12\x1e\n\x16timestamp_monotonic_ns\x18\x01 \x01(\x04\x12\r\n\x05valid\x18\x02 \x01(\x08\x12\x14\n\x0clatitude_deg\x18\x03 \x01(\x01\x12\x15\n\rlongitude_deg\x18\x04 \x01(\x01\x12\x12\n\naltitude_m\x18\x05 \x01(\x01\x12\x11\n\tspeed_mps\x18\x06 \x01(\x02\x12\x13\n\x0bheading_deg\x18\x07 \x01(\x02\x12\x13\n\x0b\x66ix_quality\x18\x08 \x01(\r\x12\x12\n\nsatellites\x18\t \x01(\r\x12\'\n\x1flast_rtcm_received_monotonic_ns\x18\n \x01(\x04\x62\x06proto3')



_GNSSFIX = DESCRIPTOR.message_types_by_name['GnssFix']
GnssFix = _reflection.GeneratedProtocolMessageType('GnssFix', (_message.Message,), {
  'DESCRIPTOR' : _GNSSFIX,
  '__module__' : 'protos.gnss_fix_pb2'
  # @@protoc_insertion_point(class_scope:natuition.gnss.GnssFix)
  })
_sym_db.RegisterMessage(GnssFix)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GNSSFIX._serialized_start=42
  _GNSSFIX._serialized_end=285
# @@protoc_insertion_point(module_scope)
